server:
    port: 1234
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcos-programadorUNT/NTTDATA-PROJECT.git
          search-paths: ClientConfiguration
          username: mhernandezb@unitru.edu.pe
          password: marcosivan1717
<<<<<<< HEAD
          default-label: master
=======
>>>>>>> 0ee4b5433c94fad48a643070b1184e5e2dd48317
  security:
    user:
      name: root
      password: s3cr3t