server:
    port: 1234
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcos-programadorUNT/NTTDATA-PROJECT.git
          search-paths: ClientConfiguration
          username: mhernandezb@unitru.edu.pe
          password: marcosivan1717
          default-label: marcos
  security:
    user:
      name: root
      password: s3cr3t