server:
  port: 8060
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/bdbank
    username: root
    password:
    data: classpath:data.sql
  application:
    name: bankingproductservice