server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: bankgatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customerservice
          uri: lb://customerservice
          predicates:
            - Path=/api/customers/**
        - id: movementservice
          uri: lb://movementservice
          predicates:
            - Path=/api/movements/**
        - id: bankingproductservice
          uri: lb://bankingproductservice
          predicates:
            - Path=/api/bankingProducts/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #colocas todos los links origen que deben acceso, en este caso "*" signfica que todos tienen acceso
            allowedHeaders:
              - Content-Type
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Authorization
              - X-Requested-With
              - requestId
              - Correlation-Id
            allowedMethods:
              - GET
              - PUT
              - PATCH
              - DELETE
              - POST
